archiv/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('jahr/<int:jahr>', views.jahr, name='jahr'),
  path('person/<int:id>', views.person, name='person'),

  path('ehrennadeltraeger/', views.ehrennadeltraeger, name='ehrennadeltraeger'),
  path('maikoenigspaare/', views.maikoenigspaare, name='maikoenigspaare'),
  path('vorsitzende/', views.vorsitzende, name='vorsitzende'),

  path('suche/', views.suche, name="suche")
]

mgarchiv/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('archiv.urls')),
    path('admin/', admin.site.urls),
]

archiv/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
  vorname           = models.CharField(max_length=255)
  nachname          = models.CharField(max_length=255)
  suchnamen         = models.CharField(max_length=255, blank=True, null=True)
  ehrennadel        = models.DateField(blank=True, null=True)
  todestag          = models.DateField(blank=True, null=True)
  ehrenmitglied_ab  = models.DateField(blank=True, null=True)

  class Meta:
    ordering = ['nachname', 'vorname']
    verbose_name_plural = "Personen"

  def __str__(self):
      return self.vorname + ' ' + self.nachname

class Maijahr(models.Model):
  jahr                      = models.PositiveSmallIntegerField(primary_key=True)
  url_vorstandsfoto         = models.URLField(blank=True, null=True)
  url_foto_maikoenigspaar   = models.URLField(blank=True, null=True)
  preis_koenig              = models.DecimalField(max_digits=10,decimal_places=2,blank=True,null=True)
  preis_remmel              = models.DecimalField(max_digits=10,decimal_places=2,blank=True,null=True)
  amtstraeger               = models.ManyToManyField(
        Person,
        through='Aemter',
    )

  class Meta:
    ordering = ['jahr']
    verbose_name_plural = "Maijahre"


  def __str__(self):
      return str(self.jahr)


class Aemter(models.Model):
  AEMTER_GROUPS = [
    {
      'Name': 'Maikönig',
      'Aemter': ['MK'],
    },
    {
      'Name': 'Maikönigin',
      'Aemter': ['MN'],
    },
    {
      'Name': 'Vorsitzender',
      'Aemter': ['VS'],
    },
    {
      'Name': '2. Vorsitzender',
      'Aemter': ['VS2'],
    },
    {
      'Name': '1. Schriftführer', 
      'Aemter': ['SF1'],
    },
    {
      'Name': '1. Kassierer', 
      'Aemter': ['KS1'],
    },
    {
      'Name': '2. Schriftführer', 
      'Aemter': ['SF2'],
    },
    {
      'Name': '2. Kassierer', 
      'Aemter': ['KS2'],
    },
    {
      'Name': '3. Schriftführer', 
      'Aemter': ['SF3'],
    },
    {
      'Name': '3. Kassierer', 
      'Aemter': ['KS3'],
    },
    {
      'Name': 'Maihauptmann', 
      'Aemter': ['MH'],
    },
    {
      'Name': 'Ehrenposten EV', 
      'Aemter': ['EPEV'],
    },
    {
      'Name': 'Sonderposten EV', 
      'Aemter': ['SPEV'],
    },
    {
      'Name': 'Vorstand', 
      'Aemter': ['MK', 'VS', 'VS2', 'SF1', 'SF2', 'SF3', 'KS1', 'KS2', 'KS3', 'MH','EPEV', 'SPEV', 'HR', 'VD'],
    },
    {
      'Name': 'Reiter', 
      'Aemter': ['MH', 'RT'],
    },
    {
      'Name': 'Hauptremmel', 
      'Aemter': ['HR'],
    },
    {
      'Name': 'Mairemmel', 
      'Aemter': ['HR', 'MR'],
    },
    {
      'Name': 'Baumträger', 
      'Aemter': ['BT'],
    },
    {
      'Name': 'Cheftechniker', 
      'Aemter': ['CT'],
    },
    {
      'Name': 'Techniker', 
      'Aemter': ['TR'],
    },
  ]
  AEMTER_CHOICES = [
    ("MK", "Maikönig"),
    ("MN", "Maikönigin"),
    ("VS", "Vorsitzender"),
    ("VS2", "2. Vorsitzender"),
    ("SF1", "1. Schriftführer"),
    ("SF2", "2. Schriftführer"),
    ("SF3", "3. Schriftführer"),
    ("KS1", "1. Kassierer"),
    ("KS2", "2. Kassierer"),
    ("KS3", "3. Kassierer"),
    ("MH", "Maihauptmann"),
    ("SPEV", "Sonderposten EV"),
    ("EPEV", "Ehrenposten EV"),
    ("VD", "Vorstand"),
    ("RT", "Reiter"),
    ("HR", "Hauptremmel"),
    ("MR", "Mairemmel"),
    ("BT", "Baumträger"),
    ("CT", "Cheftechniker"),
    ("TR", "Techniker"),
  ]
  person      = models.ForeignKey(Person, on_delete=models.CASCADE)
  maijahr     = models.ForeignKey(Maijahr, on_delete=models.CASCADE)
  amt         = models.CharField(max_length=8,choices=AEMTER_CHOICES)
  reihenfolge = models.SmallIntegerField(blank=True, null=True)

  class Meta:
    ordering = ['maijahr', 'amt', 'reihenfolge', 'person']

  def __str__(self):
    return str(self.maijahr) + ' ' + self.amt +  ' ' + str(self.person)
    

archiv/views.py
from django.http import HttpResponse
from django.template import loader
from itertools import groupby
from .models import Maijahr, Person, Aemter
from .helpers import Helpers
from .filters import PersonFilter
from datetime import datetime
from django.db.models.functions import Concat
from django.db.models import Q

from django.shortcuts import redirect

# Create your views here.
def home(request):
  template = loader.get_template('home.html')
  context = {
  }
  return HttpResponse(template.render(context, request))

def jahr(request, jahr):
  maijahr = Maijahr.objects.get(jahr=jahr)
  maijahre = Maijahr.objects.all()
  aemter= [{'amt': amt, 'personen':list(group)} for amt, group in groupby(maijahr.aemter_set.order_by('amt'), lambda x: x.amt)]
  ehrenmitglieder = Person.objects.filter(ehrenmitglied_ab__lte=str(maijahr.jahr)+'-12-31').filter(Q(todestag__isnull=True) | Q(todestag__gte=str(maijahr.jahr)+'-01-01')).order_by('ehrenmitglied_ab')

  order = [key for (key, value) in Aemter.AEMTER_CHOICES]
  aemter.sort(key= lambda x: order.index(x['amt']))

  try:
    maikoenig   = [x['personen'] for x in aemter if x['amt']=='MK'][0][0].person
    maikoenigin = [x['personen'] for x in aemter if x['amt']=='MN'][0][0].person
  except IndexError:
    maikoenig = None
    maikoenigin = None

  novd = not any(ele['amt'] == 'VD' for ele in aemter)

  template = loader.get_template('maijahr.html')
  context = {
    'maijahr': maijahr, 
    'maijahre' : maijahre,
    'maikoenig': maikoenig,
    'maikoenigin': maikoenigin,
    'aemter': aemter,
    'ehrenmitglieder': ehrenmitglieder,
    'keinVorstand': novd,
  }
  return HttpResponse(template.render(context, request))

def jahre(request):
  maijahre = Maijahr.objects.all().values()
  template = loader.get_template('maijahre.html')
  context = {
    'maijahre': maijahre,
  }
  return HttpResponse(template.render(context, request))

def person(request, id):
  person = Person.objects.get(id=id)
  #aemter = Aemter.objects.filter(person_id=id).order_by('amt')
  #aemter = [{'amt': x['Name'],'jahre':person.aemter_set.filter(amt__in=x['Aemter'])} for x in Aemter.AEMTER_GROUPS]
  
  aemter_maijahre = [{'amt': x['Name'],'jahre':[amt.maijahr for amt in person.aemter_set.filter(amt__in=x['Aemter'])]} for x in Aemter.AEMTER_GROUPS]
  
  if person.ehrenmitglied_ab:
    ehrenmitglied_jahre = Maijahr.objects.filter(jahr__gte=person.ehrenmitglied_ab.year).filter(jahr__lte=(person.todestag or datetime.today()).year)
    aemter_maijahre = [x | {'jahre': x['jahre'] if x['amt']  != 'Vorstand' else list(x['jahre']) + list(ehrenmitglied_jahre )} for x in aemter_maijahre]

  aemter = [x | {'jahre_str': ', '.join(Helpers.list_to_range_strs([jahr.jahr for jahr in x['jahre']]))
                 , 'jahre': x['jahre']}  for x in aemter_maijahre]

  template = loader.get_template('person.html')
  context = {
    'person': person,
    'aemter': aemter,
    'ehrennadel_maifest': person.ehrennadel and person.ehrennadel.month == 5 and person.ehrennadel.day == 1,
  }
  return HttpResponse(template.render(context, request))

def ehrennadeltraeger(request):
  ehrennadeltraeger = Person.objects.exclude(ehrennadel__isnull=True).order_by('ehrennadel')
  template = loader.get_template('ehrennadeltraeger.html')
  context = {
    'ehrennadeltraeger': [{'jahr': jahr, 'personen':list(group)} for jahr, group in groupby(ehrennadeltraeger, lambda x: x.ehrennadel.year)]
  }
  return HttpResponse(template.render(context, request))

def maikoenigspaare(request):
  maikoenigspaare = Aemter.objects.filter(amt__in=['MK','MN'])
  template = loader.get_template('maikoenigspaare.html')
  context = {
    'maikoenigspaare': [{'jahr': jahr, 'paar':list(group)} for jahr, group in groupby(maikoenigspaare, lambda x: x.maijahr.jahr)],
  }
  return HttpResponse(template.render(context, request))

def vorsitzende(request):
  vosis = Aemter.objects.filter(amt='VS').filter(maijahr__gte='1927').order_by('person_id', 'maijahr_id')
  vosis=[{'person': person, 'jahre':list(aemter)} for person, aemter in groupby(vosis, lambda x: x.person)]

  vosis=[{'person': p['person'], 'jahre':[x.maijahr for x in list(p['jahre'])], 'jahre_str':', '.join(Helpers.ranges_to_strs(Helpers.to_ranges([x.maijahr.jahr for x in list(p['jahre'])])))} for p in vosis]

  vosis.sort(key= lambda x:x['jahre'][0].jahr )

  template = loader.get_template('vorsitzende.html')
  context = {
    'vorsitzende': vosis
  }
  return HttpResponse(template.render(context, request))

def suche(request):
  q = request.GET.get('q')

  try:
    Maijahr.objects.get (jahr=q)
    return redirect(jahr, q)
  except:
    q_split = q.split(' ')
    personen =  Person.objects.annotate(fullname=Concat('vorname','nachname','suchnamen')).all()
    for q1 in q_split:
      personen =  personen.filter(fullname__icontains=q1)  

    template = loader.get_template('suche.html')
    context = {
      'q': q,
      'ergebnis': personen,
    }
    return HttpResponse(template.render(context, request))

archiv/templates/_inc_popoverjahre.html
<span>
{% for j in jahre %}
  <a href=&quot/jahr/{{ j }}&quot>{{ j }}</a>{% if not forloop.last %},{% endif %}
{% endfor %}
</span>

archiv/templates/_navbar.html
{% url 'home' as home_url %}
{% url 'maikoenigspaare' as maikoenigspaare_url %}
{% url 'ehrennadeltraeger' as ehrennadeltraeger_url %}
{% url 'vorsitzende' as vorsitzende_url %}
{% url 'suche' as suche_url %}
{% load static %}

<nav class="navbar navbar-expand-md">
  <div class="container-fluid">
    <a class="navbar-brand mb-0 h1 order-1" href="{{home_url}}">Archiv</a>
    <div class="p-2"><img id='schleife' height="50%" src="{% static 'img/schleife.png' %}"></div>
    <button class="navbar-toggler order-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse order-4 order-md-2" id="navbarNav">
      <ul class="navbar-nav ">
        <li class="nav-item"><a class="nav-link {% if request.path == maikoenigspaare_url %} active {%endif%}" href="{{maikoenigspaare_url}}">Maikönigspaare</a></li>
        <li class="nav-item"><a class="nav-link {% if request.path == ehrennadeltraeger_url %} active {%endif%}" href="{{ehrennadeltraeger_url}}">Ehrennadelträger</a></li>
        <li class="nav-item"><a class="nav-link {% if request.path == vorsitzende_url %} active {%endif%}" href="{{vorsitzende_url}}">Vorsitzende</a></li>
      </ul>
    </div>
    <div class="nav-item dropdown order-2 ms-auto">
      <button class="btn btn-link nav-link py-2 px-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button" aria-expanded="false" data-bs-toggle="dropdown" data-bs-display="static">
        <svg class="bi my-1 theme-icon-active"><use href="#moon-stars-fill"></use></svg>
      </button>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="bd-theme" style="--bs-dropdown-min-width: 8rem;">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light">
            <svg class="bi me-2 opacity-50 theme-icon"><use href="#sun-fill"></use></svg>
            Hell
            <svg class="bi ms-auto d-none"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="dark">
            <svg class="bi me-2 opacity-50 theme-icon"><use href="#moon-stars-fill"></use></svg>
            Dunkel
            <svg class="bi ms-auto d-none"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="auto">
            <svg class="bi me-2 opacity-50 theme-icon"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>
    <form action="{% url 'suche' %}" class="d-flex d-none d-md-block order-5" role="search">
      <div class="input-group">
      <input name="q" class="form-control" type="search" placeholder="Name oder Jahr" aria-label="Suche">
      <button class="btn btn-outline-primary" type="submit"><i class="bi bi-search"></i></button>
      </div> 
    </form>
  </div>
</nav>
<div class="container-fluid mb-2 d-md-none">
  <form action="{% url 'suche' %}" class="d-flex" role="search">
    <div class="input-group">
    <input name="q" class="form-control" type="search" placeholder="Name oder Jahr" aria-label="Suche">
    <button class="btn btn-outline-primary" type="submit"><i class="bi bi-search"></i></button>
    </div> 
  </form>
</div>

archiv/templates/ehrennadeltraeger.html
{% extends "_master.html" %}

{% block title %}
  Ehrennadelträger - Archiv Maigesellschaft Derichsweiler
{% endblock %}


{% block content %}

  <h2>Ehrennadelträger</h2>
  
  <table class="table table-sm">
    <thead><tr>
    <th scope="col">Name</th>
    <th scope="col">Jahr der Ehrung</th>
    </tr></thead>
    <tbody>
      {% for entjahr in ehrennadeltraeger %}
        {% for p in entjahr.personen %}
          <tr>
            <td><a href="/person/{{ p.id }}">{{ p }}</a>{% if p.todestag %}&nbsp;†{% endif %}
            </td>
            {% if forloop.first %}
            <td rowspan="{{entjahr.personen|length }}"><a href="/jahr/{{ entjahr.jahr }}">{{ entjahr.jahr }}</a></td>
            {% endif %} 
          </tr>
          {% endfor %}
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

archiv/templates/home.html
{% extends "_master.html" %}

{% block title %}
  Archiv Maigesellschaft Derichsweiler
{% endblock %}


{% block content %}

  <p class="lead py-4 text-center">Willkommen im Archiv der Maigesellschaft&nbsp;Derichsweiler</p>

{% endblock %}

archiv/templates/maijahr.html
{% extends "_master.html" %}

{% block title %}
  Jahr {{ maijahr.jahr }} Archiv Maigesellschaft Derichsweiler
{% endblock %}

{% block content %}
  <h2>Jahr {{ maijahr.jahr }}</h2>
  <div class="list-group list-group-horizontal position-relative overflow-auto mb-2">
    {% for j in maijahre %}
      <a href="{% url 'jahr' j.jahr %}" id="link{{j.jahr}}" class="list-group-item list-group-item-action {% if j.jahr == maijahr.jahr %} active {% endif %}">{{ j.jahr }}</a>
    {% endfor %}
  </div>
  <div class="container">
    <div class="row gap-3">
      <div class="col order-md-2">
        <div class="d-flex flex-row flex-md-column align-items-center gap-3 gallery">
          {% if maijahr.url_foto_maikoenigspaar %}
            <div data-bs-theme="dark" class="card text-center mg-foto-maikoenigspaar">
              <a href="{{ maijahr.url_foto_maikoenigspaar }}" class="gallery-link">
                <img src="{{ maijahr.url_foto_maikoenigspaar }}" class="card-img" style="max-height: 60vh;" title="Maikönigspaar {{ maikoenig }} und {{ maikoenigin }}">
              </a>
              <div class="card-img-overlay bg-dark rounded-bottom"  style="--bs-bg-opacity: .7; top:auto; border-top-left-radius: 0; border-top-right-radius: 0;padding:0.25rem;">
                <p class="card-text" style="text-overflow: ellipsis; overflow: hidden; -webkit-box-orient: vertical; -webkit-line-clamp: 3; display: -webkit-box;">Maikönigspaar <a href="/person/{{ maikoenig.id }}">{{ maikoenig }}</a> und <a href="/person/{{ maikoenigin.id }}">{{ maikoenigin }}</a></p>
              </div>
            </div>
          {% endif %}
          {% if maijahr.url_vorstandsfoto %}
            <div data-bs-theme="dark" class="card text-center  mg-foto-vorstand">
              <a href="{{ maijahr.url_vorstandsfoto }}" class="gallery-link">
                <img src="{{ maijahr.url_vorstandsfoto }}" class="card-img" style="max-height: 60vh;" title="Vorstand im Jahr {{ maijahr.jahr }}">
              </a>
              <div class="card-img-overlay bg-dark" style="--bs-bg-opacity: .7; top:auto; border-top-left-radius: 0; border-top-right-radius: 0; padding:0.25rem;">
                <p class="card-text" style="text-overflow: ellipsis; overflow: hidden; white-space: nowrap;">Vorstand im Jahr {{ maijahr.jahr }}</p>
              </div>
            </div>
          {% endif %}
        </div> 
      </div>
      <div class="col-12 col-md-6 order-md-1">
        <table class="table table-sm">
          <thead><tr>
          <th>Amt</th>
          <th>Person</th>
          </tr></thead>
          <tbody>
            {% for x in aemter %}
              {% if x.amt == 'VD' %}
                {%for e in ehrenmitglieder %}
                  <tr>
                    {% if forloop.counter0 == 0 %}
                    <td rowspan="{{ehrenmitglieder|length }}">Ehrenmitglied</td>
                    {% endif %}
                    <td><a href="/person/{{ e.id }}">{{ e }}</a></td>
                  </tr>
                {% endfor %}
              {% endif %}
              {% for p in x.personen %}
                
                <tr>
                  {% if forloop.counter0 == 0 %}
                  <td rowspan="{{x.personen|length }}">{{p.get_amt_display}}</td>
                  {% endif %}
                  <td><a href="/person/{{ p.person.id }}">{{ p.person }}</a></td>
                </tr>
              {% endfor %}
            {% endfor %}
            {% if keinVorstand %} {%for e in ehrenmitglieder %}
            <tr>
              {% if forloop.counter0 == 0 %}
              <td rowspan="{{ehrenmitglieder|length }}">Ehrenmitglied</td>
              {% endif %}
              <td><a href="/person/{{ e.id }}">{{ e }}</a></td>
            </tr>
            {% endfor %}{% endif %}
          </tbody>
        </table>
      </div> 
    </div>
  </div>
  <script type="application/javascript">
    document.getElementById("link{{maijahr.jahr}}").scrollIntoView({
      behavior: "auto",
      block: "end",
      inline: "center"
    });
   </script>
{% endblock %}

archiv/templates/maijahre.html
{% extends "_master.html" %}

{% block title %}
  Archiv Maigesellschaft Derichsweiler
{% endblock %}


{% block content %}

  <h2>Jahre</h2>
  
  <div class="list-group">
    {% for x in maijahre %}
      <a  class="list-group-item  list-group-item-action" href="/jahr/{{x.jahr}}">{{ x.jahr }}</a>
    {% endfor %}
  </div>

{% endblock %}

archiv/templates/maikoenigspaare.html
{% extends "_master.html" %}

{% block title %}
   Maikönigspaare - Archiv Maigesellschaft Derichsweiler
{% endblock %}


{% block content %}

  <h2>Maikönigspaare</h2>
  
  <table class="table table-sm">
    <thead><tr>
    <th>Jahr</th>
    <th>Maikönigspaar</th>
    </tr></thead>
    <tbody>
      {% for x in maikoenigspaare %}
        <tr>
          <td><a href="/jahr/{{ x.jahr }}">{{ x.jahr }}</a></td>
          <td><a href="/person/{{ x.paar.0.person.id }}">{{ x.paar.0.person }}</a> und <a href="/person/{{ x.paar.1.person.id }}">{{ x.paar.1.person }}</a> </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

archiv/templates/person.html
{% extends "_master.html" %}
{% load popover_jahre %}

{% block title %}
  {{ person }} Archiv Maigesellschaft Derichsweiler
{% endblock %}


{% block content %}

  <h2>{{ person }}</h2>
  {% if person.todestag %}
    <p>† {{person.todestag|date:"d.m.Y"}}  </p>
  {% endif %}
  <table class="table">
    <thead><tr>
    <th>Amt</th>
    <th>Jahr</th>
    </tr></thead>
    <tbody>
      {% for x in aemter %}
      {% if x.jahre_str %}
        <tr>
          <td>{{ x.amt }} </td>
          <td>
            <a tabindex="0" class="popover-toggle" data-bs-title="zu Jahren" data-bs-html="true" data-bs-trigger="focus" data-bs-toggle="popover" data-bs-title="Popover title" data-bs-content="{% popover_jahre x.jahre %}">
              {{ x.jahre_str }} 
            </a>
          </td>
        </tr>
        {% endif %}
      {% endfor %}
    </tbody>
  </table>

  {% if person.ehrenmitglied_ab %}
  <p>{{ person }} wurde im Jahr {{person.ehrenmitglied_ab|date:"Y"}} zum Ehrenmitglied der Maigesellschaft Derichsweiler ernannt.</p>
  {% endif %}

  {% if person.ehrennadel %}
  <p>{{ person }} wurde 
      {% if ehrennadel_maifest %} 
        auf dem Maifest {{person.ehrennadel|date:"Y"}} 
      {% else %}
        am {{person.ehrennadel|date:"j. F Y"}} 
      {% endif %} die Goldene Ehrennadel der Maigesellschaft Derichsweiler verliehen.</p>
  {% endif %}

{% endblock %}

archiv/templates/suche.html
{% extends "_master.html" %}

{% block title %}
  Suche Archiv Maigesellschaft Derichsweiler
{% endblock %}


{% block content %}
  <h2>Suche nach „{{ q }}“</h2>
  <div class="list-group">
    {% for person in ergebnis %}
    <a class="list-group-item list-group-item-action" href="/person/{{ person.id }}">{{ person }}</a>
    {% endfor %}
  </div>
{% endblock %}

archiv/templates/vorsitzende.html
{% extends "_master.html" %}
{% load popover_jahre %}

{% block title %}
   Vorsitzende - Archiv Maigesellschaft Derichsweiler
{% endblock %}


{% block content %}

  <h2>Vorsitzende</h2>
  
  <table class="table table-sm">
    <thead><tr>
    <th>Name</th>
    <th>Jahre</th>
    </tr></thead>
    <tbody>
      {% for x in vorsitzende %}
        <tr>
          <td><a href="/person/{{ x.person.id }}">{{ x.person }}</a></td>
          <td>
            <a tabindex="0" class="popover-toggle" data-bs-title="zu Jahren" data-bs-html="true" data-bs-trigger="focus" data-bs-toggle="popover" data-bs-title="Popover title" data-bs-content="{% popover_jahre x.jahre %}">
              {{ x.jahre_str }} 
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}